### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by thachck** [japananh/japananh.github.io#1]
Góp ý nhỏ - có vẻ nhiều bài post của bạn sau bài [Tôi học được gì trong 6 tháng đầu năm 2022](https://japananh.github.io/vi/p/toi-hoc-duoc-gi-trong-6-thang-dau-nam-2022/) đều có ảnh không parsed được từ markdown sang img tag.

Mình dùng safari 😄 

![thachck 2022-11-25 at 22 23 32](https://user-images.githubusercontent.com/640707/204015638-69276a4d-4f54-4e4d-983b-bab8e4dc7a4c.png)

**Comment by japananh** [comment]
Fixed. [Check it out](https://thewriteratheart.com/p/toi-hoc-duoc-gi-trong-6-thang-dau-nam-2022/#t%C3%B4i-mu%E1%BB%91n-l%C3%A0m-g%C3%AC-trong-6-th%C3%A1ng-t%E1%BB%9Bi)
